# Generated by Django 2.2 on 2021-12-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frereAPP', '0002_auto_20211211_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenitems',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='frereAPP.sections'),
            preserve_default=False,
        ),
    ]
