# Generated by Django 2.2 on 2021-12-12 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frereAPP', '0003_kitchenitems_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenitems',
            name='html_tag',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
